<a href="https://colab.research.google.com/github/Ankita-k-codes/Ankita-k-codes.github.io/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy Numerical Python

adv = mathematical operation
fasteer operation

In [2]:
import numpy as np

List vs Numpy - time taken

In [3]:
from time import process_time

Time taken by a list

In [4]:
python_list = [i for i in range(10000)]

start_time = process_time()

python_list = [i+5 for i in python_list]

end_time = process_time()

print(end_time - start_time)

0.0005063620000003155


In [6]:
np_array = np.array([i for i in range(10000)])

start_time = process_time()

np_array += 5

end_time = process_time()

print(end_time - start_time)


0.0009019999999999584


Numpy Arrays

In [7]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
#creating a 1D array

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [10]:
a.shape
#rows nd colom


(4,)

In [11]:
b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
b.shape

[[1 2 3 4]
 [5 6 7 8]]


(2, 4)

In [12]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype = float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [17]:
#intial placeholder in numpy array

#create a numpy array of zerp

d = np.zeros((3,3))
print(d)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [16]:
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [18]:
b = np.random.randint(1,10, (5,5))
print(b)

[[5 3 1 9 4]
 [1 4 7 4 9]
 [9 3 9 3 8]
 [3 2 1 3 5]
 [2 1 8 8 9]]


In [21]:
de = np.linspace(10,30,10)
print(de)

[10.         12.22222222 14.44444444 16.66666667 18.88888889 21.11111111
 23.33333333 25.55555556 27.77777778 30.        ]
